apiVersion: apps/v1
kind: Deployment
metadata:
  name: courses-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: courses
  template:
    metadata:
      labels:
        app: courses
    spec:
      containers:
        - name: courses
          image: courses:latest
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: courses-srv-cl-ip
spec:
  selector:
    app: courses
  ports:
    - name: courses
      protocol: TCP
      port: 3000
      targetPort: 3000
